fastlane_version "2.210.1"

default_platform :android

platform :android do
  desc "Deploy to Google Play"
  lane :deploy do
    upload_to_play_store(
      package_name: "com.example.dracula",
      aab: "app-release.aab",
      track: "production",
      json_key: "google-play.json"
    )
  end
end

platform :ios do
  desc "Deploy to TestFlight/App Store"
  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_PRIVATE_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: "AuthKey.p8"
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: "*.ipa"
    )
  end
end